openapi: 3.0.0
x-stoplight:
  id: h1iobyygo7ibb
info:
  title: GITAPIProject3.0Y
  version: '1.0'
  description: hnhtestyruyttgahhdeadmjnbjbkhjkjnvnh
  contact:
    name: yresrsrs
    url: 'http://localhost:3000khuyuyuy8688868'
    email: anki@gmail.com
  termsOfService: 'http://localhost:30002424i90uu'
  license:
    name: post-user66
    url: 'https://apy76i8yuiut8iyi.example.com'
servers:
  - url: 'http://localhost:3000'
    description: serverrrrrrrrrrrr
paths:
  '/users/{userId}':
    id: 7osjmqd88xujq
    patch:
      x-stoplight:
        id: ozaj00suhb3ax
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
              properties:
                firstName:
                  type: array
                  items:
                    x-stoplight:
                      id: emuz7jg00cdcr
                    type: array
                    items:
                      x-stoplight:
                        id: p7g7tc7108p32
                      enum: []
                lastName:
                  type: integer
                email:
                  type: boolean
                  default: true
                dateOfBirth:
                  type: string
                  format: date
                tcace:
                  type: string
                  x-stoplight:
                    id: 8kkfh8n6uyyfa
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: od2nf1cgr7y3i
components:
  schemas:
    User:
      title: User
      x-stoplight:
        id: kgn9m29gvksri
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: kylrmlzfbhap0
        firstName:
          type: string
          x-stoplight:
            id: hn33ot81vkswf
        lastName:
          type: string
          x-stoplight:
            id: h57suhqvz110k
        email:
          type: string
          format: email
          x-stoplight:
            id: n3jlxok5fxetw
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: 1ka1dq4ukq3qp
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: 3g4zc77zm46eg
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: n9iovpoe1ox5k
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
  securitySchemes:
    apiKey_1:
      type: http
      scheme: bearer
    apiKey_2:
      type: http
      scheme: basic
    apiKey_3:
      name: apiKey
      type: apiKey
      in: cookie
    apiKey_4:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'localhost:3000676686868868'
          refreshUrl: 'https://api44444.example.com'
          scopes:
            scope_1: jgjguhuututyu
            scope_2: ghffydtdy
    apiKey_5:
      type: openIdConnect
      openIdConnectUrl: 'https://api.example.com'
      description: test
security:
  - apiKey_3: []
    apiKey_1: []
    apiKey_5: []
    apiKey_2: []
x-extension-1: 67688b yitt t
x-extension-2: 67688b yitt t
x-extension-3: 67688b yitt t
x-internal: true
